---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-doom-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: kube-doom-pod
  template:
    metadata:
      labels:
        app: kube-doom-pod
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - image: storaxdev/kubedoom:0.5.0
          name: kubedoom
          ports:
            - containerPort: 5900
              protocol: TCP